version: '3.8'

services:
  prometheus:
    image: prom/prometheus:v2.47.0
    container_name: prometheus_test
    volumes:
      - ./prometheus-test.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    healthcheck:
      test: ["CMD", "wget", "--spider", "http://localhost:9090/-/healthy"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - test-network

  grafana:
    image: grafana/grafana:10.0.3
    container_name: grafana_test
    ports:
      - "3000:3000"
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/health"]
      interval: 10s
      timeout: 5s
      retries: 5
    depends_on:
      prometheus:
        condition: service_healthy
    networks:
      - test-network

  elasticsearch:
    image: elasticsearch:8.15.2
    container_name: elasticsearch_test
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    ports:
      - "9200:9200"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9200/_cluster/health?wait_for_status=yellow"]
      interval: 10s
      timeout: 5s
      retries: 10
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    networks:
      - test-network

  kibana:
    image: kibana:8.15.2
    container_name: kibana_test
    ports:
      - "5601:5601"
    depends_on:
      elasticsearch:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5601/api/status"]
      interval: 10s
      timeout: 5s
      retries: 10
    networks:
      - test-network

  filebeat:
    image: docker.elastic.co/beats/filebeat:8.15.2
    container_name: filebeat_test
    volumes:
      - ./filebeat-test.yml:/usr/share/filebeat/filebeat.yml:ro
      - ./logs:/logs
    depends_on:
      elasticsearch:
        condition: service_healthy
    networks:
      - test-network

volumes:
  elasticsearch_data:

networks:
  test-network:
    driver: bridge