server:
  port: 8082

spring:
  data:
    mongodb:
      uri: mongodb://mongodb:27017/wallet_service
      uuid-representation: standard
      auto-index-creation: true

springdoc:
  api-docs:
    path: /v3/api-docs
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
    enabled: true